/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelChequeBBVA.java
 *
 * Created on Jul 14, 2009, 5:48:49 PM
 */

package com.bizitglobal.tarjetafiel.view;

/**
 *
 * @author Mario
 */
public class PanelChequeBBVA extends javax.swing.JPanel {

    /** Creates new form PanelChequeBBVA */
    public PanelChequeBBVA() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDiaEmitido = new javax.swing.JLabel();
        lblMesEmitido = new javax.swing.JLabel();
        lblAnioEmitido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblImportePesos = new javax.swing.JLabel();
        lblDiaPagar = new javax.swing.JLabel();
        lblMesPagar = new javax.swing.JLabel();
        lblAnioPagar = new javax.swing.JLabel();
        lblImporteLetra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setLayout(null);

        lblDiaEmitido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiaEmitido.setText("lbldiaEmitido");
        add(lblDiaEmitido);
        lblDiaEmitido.setBounds(180, 40, 60, 14);

        lblMesEmitido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMesEmitido.setText("lblMesEmitido");
        add(lblMesEmitido);
        lblMesEmitido.setBounds(250, 60, 110, 14);

        lblAnioEmitido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAnioEmitido.setText("lblAnioEmitido");
        add(lblAnioEmitido);
        lblAnioEmitido.setBounds(380, 60, 80, 14);

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre.setText("lblNombre");
        add(lblNombre);
        lblNombre.setBounds(180, 103, 320, 14);

        lblImportePesos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblImportePesos.setText("lblImportePesos");
        add(lblImportePesos);
        lblImportePesos.setBounds(485, 15, 150, 20);

        lblDiaPagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiaPagar.setText("lblDiaPagar");
        lblDiaPagar.setName("diaPagar"); // NOI18N
        add(lblDiaPagar);
        lblDiaPagar.setBounds(140, 80, 35, 14);

        lblMesPagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMesPagar.setText("lblMesPagar");
        add(lblMesPagar);
        lblMesPagar.setBounds(190, 80, 170, 14);

        lblAnioPagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAnioPagar.setText("lblAnioPagar");
        add(lblAnioPagar);
        lblAnioPagar.setBounds(380, 80, 80, 14);

        lblImporteLetra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblImporteLetra.setText("lblImporteLetra");
        add(lblImporteLetra);
        lblImporteLetra.setBounds(220, 127, 300, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Documents and Settings\\Eze\\My Documents\\NetBeansProjects\\ImpresionCheque\\images\\chequeBBVA_1.JPG")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 677, 290);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblAnioEmitido;
    public javax.swing.JLabel lblAnioPagar;
    public javax.swing.JLabel lblDiaEmitido;
    public javax.swing.JLabel lblDiaPagar;
    public javax.swing.JLabel lblImporteLetra;
    public javax.swing.JLabel lblImportePesos;
    public javax.swing.JLabel lblMesEmitido;
    public javax.swing.JLabel lblMesPagar;
    public javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public int getHeight() {
        return jLabel1.getHeight();
    }

    @Override
    public int getWidth() {
        return jLabel1.getWidth();
    }

}
