/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResultadoImpresion.java
 *
 * Created on Jul 23, 2009, 9:45:37 AM
 */
package com.bizitglobal.tarjetafiel.view;

import com.bizitglobal.tarjetafiel.fondos.negocio.Cheque;
import com.bizitglobal.tarjetafiel.fondos.negocio.ChequeEstado;
import com.bizitglobal.tarjetafiel.fondos.negocio.ChequeHistorial;
import com.bizitglobal.tarjetafiel.fondos.service.impl.ChequeServiceImpl;
import com.bizitglobal.tarjetafiel.fondos.service.impl.ChequeraServiceImpl;
import com.bizitglobal.tarjetafiel.impresioncheque.ChequeBbva;
import com.bizitglobal.tarjetafiel.impresioncheque.Impresora;
import com.bizitglobal.tarjetafiel.impresioncheque.ChequeBsj;
import com.bizitglobal.tarjetafiel.impresioncheque.ChequeStandartBank;
import com.bizitglobal.tarjetafiel.impresioncheque.modelos.ModelLocator;
import java.awt.Frame;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class ResultadoImpresion extends javax.swing.JDialog {

    /** Creates new form ResultadoImpresion */
    private ChequeServiceImpl chequeServiceImpl;
    private ChequeraServiceImpl chequeraServiceImpl;
    private ModeloProcesados modProcesados;

    public ResultadoImpresion() {
        super(new Frame(), true);
        initComponents();

       
        
        modProcesados = new ModeloProcesados();
        ModelLocator modelLocator = ModelLocator.getInstance();

        ModeloProcesados modelo = (ModeloProcesados) tblResultado.getModel();
        modelo.setList(modelLocator.chequeModel.getListCheques());
        tblResultado.setModel(modelo);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        btnConfirmar = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();
        btnReimprimir = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        btnSelTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        tblResultado.setModel(new ModeloProcesados());
        jScrollPane1.setViewportView(tblResultado);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnAnular.setText("Anular");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        btnReimprimir.setText("Reimprimir");
        btnReimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReimprimirActionPerformed(evt);
            }
        });

        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        btnSelTodos.setText("Sel. todos");
        btnSelTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSelTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTerminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReimprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(btnAnular, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnular, btnConfirmar, btnReimprimir, btnSelTodos, btnTerminar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReimprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTerminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btnSelTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAnular, btnConfirmar, btnReimprimir, btnSelTodos, btnTerminar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeProcesados(ModeloProcesados modeloProcesados) {
        for (MainView.ChequeWape chequeWape : (LinkedList<MainView.ChequeWape>) modeloProcesados.getList()) {
            ((ModeloProcesados) tblResultado.getModel()).borraChequeWraper(chequeWape);
        }
    }
    private void procesarCheque(LinkedList<MainView.ChequeWape> list, String accion){
        for (MainView.ChequeWape cheque : list) {

            if (cheque.getAccionEstado()) {
                cheque.getCheque().setProcesado('S');
                cheque.setAccion(accion);
                modProcesados.anhadeChequeWraper(cheque);
            }
        }
        removeProcesados(modProcesados);
    }

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        procesarCheque(((ModeloProcesados) tblResultado.getModel()).getList(), "C");
        
//********************CHEQUE HISTORIAL PENDIETE!!!!!
//                    LinkedList<ChequeHistorial> chequeHistorialList = (LinkedList<ChequeHistorial>) cheque.getHistorial();
//
//                    ChequeHistorial chequeHistorial = new ChequeHistorial();
//                    chequeHistorial.setAsientoItem(chequeHistorialList.getLast().getAsientoItem());
//                    chequeHistorial.setCheque(chequeHistorialList.getLast().getCheque());
//                    chequeHistorial.setChequeEstado(new ChequeEstado(new Long("8")));
//                    chequeHistorial.setMovimientoMP(chequeHistorialList.getLast().getMovimientoMP());
//                    chequeHistorial.setTimestamp(new Date());
//                    //chequeHistorial.setIdChequeHistorial(idChequeHistorial);
//                    cheque.getHistorial().add(chequeHistorial);

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        // TODO add your handling code here:
        
        //int i = JOptionPane.showMessageDialog(new Frame(),
        //            new String("Debe confirmar o anular los cheques pendientes."), "Impresion Cheques", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
        //JOptionPane.YES_OPTION == i

        if (((ModeloProcesados) tblResultado.getModel()).getList().size() > 0) {
                JOptionPane.showMessageDialog(this, new String("Debe confirmar o anular los cheques pendientes."),
                "Impresion Cheques", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ModelLocator.getInstance().chequeProcesadosModel.setListCheques(modProcesados.getList());
            ((MainView)ModelLocator.getInstance().frameModel.getFrameRef()).returnFromResultadoImpresion();
            this.dispose();
        }

}//GEN-LAST:event_btnTerminarActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        // TODO add your handling code here:
        procesarCheque(((ModeloProcesados) tblResultado.getModel()).getList(), "A");
    }//GEN-LAST:event_btnAnularActionPerformed

    private void btnReimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReimprimirActionPerformed
        // TODO add your handling code here:
        for (MainView.ChequeWape cheque : (LinkedList<MainView.ChequeWape>) ((ModeloProcesados) tblResultado.getModel()).getList()) {
            imprimirCheque(cheque.getCheque());
        }
        
    }//GEN-LAST:event_btnReimprimirActionPerformed

    private void btnSelTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelTodosActionPerformed
        // TODO add your handling code here:
        ModeloProcesados mod= new ModeloProcesados();
        LinkedList<MainView.ChequeWape> listche=new LinkedList<MainView.ChequeWape>();
        for(MainView.ChequeWape cheque: (LinkedList<MainView.ChequeWape>)((ModeloProcesados) tblResultado.getModel()).getList()){
            cheque.setAccionEstado(!cheque.getAccionEstado());
            listche.add(cheque);
        }
        mod.setList(listche);
        tblResultado.setModel(mod);
    }//GEN-LAST:event_btnSelTodosActionPerformed

    public void imprimirCheque(Cheque cheque) {
        Impresora print = ModelLocator.getInstance().impresoraSeleccionada.getImpresoraSeleccionada();
        String eval = cheque.getBancoPropio().getIdBancoPropio().toString();
        switch (Integer.parseInt(eval)) {
            case 1:
                //DE SAN JUAN S.A.
                ChequeBsj chequeBsj = new ChequeBsj(cheque);
                print.imprimir(chequeBsj);
                break;
            case 2:
                //FRANCES
                ChequeBbva chequeBbva = new ChequeBbva(cheque);
                print.imprimir(chequeBbva);
                break;
            case 3:
                //STANDARD BANK
                ChequeStandartBank chequeStandartBank = new ChequeStandartBank(cheque);
                print.imprimir(chequeStandartBank);
                break;
            default:
                System.out.println("error");
                break;
        }
//        STANDARD BANK                                      3
//        FRANCES                                            2
//        DE SAN JUAN S.A.                                   1

    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnReimprimir;
    private javax.swing.JButton btnSelTodos;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultado;
    // End of variables declaration//GEN-END:variables
}
